FROM python:3.12.3-slim

WORKDIR /app

COPY alembic/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY web_app/src/models web_app/src/models
COPY alembic.ini .
COPY alembic alembic

CMD ["sleep", "infinity"]
# CMD ["alembic", "upgrade", "head"]