services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      # network: host
      # args:
      #  - http_proxy=http://127.0.0.1:10808
      #  - https_proxy=http://127.0.0.1:10808
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    # ports:
    #  - "8001:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web_app/src/static:/app/static:ro
    depends_on:
      - web
    restart: unless-stopped

  alembic:
    build:
      context: .
      dockerfile: Dockerfile.alembic
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./alembic/versions:/app/alembic/versions

volumes:
  postgres_data:
  redis_data: