"""update personnel reports

Revision ID: 25625c9da1d9
Revises: 6fc3fdc8c301
Create Date: 2026-06-22 12:54:26.022200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25625c9da1d9'
down_revision: Union[str, Sequence[str], None] = '6fc3fdc8c301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineries', 'total_personnel')
    op.drop_column('machineries', 'personnel')
    op.add_column('reports', sa.Column('total_personnel', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('personnel', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('current_personnel', sa.Integer(), nullable=False))
    op.alter_column('reports', 'leadership',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'leadership',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('reports', 'current_personnel')
    op.drop_column('reports', 'personnel')
    op.drop_column('reports', 'total_personnel')
    op.add_column('machineries', sa.Column('personnel', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('machineries', sa.Column('total_personnel', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
