"""update tables

Revision ID: 2ca3403245cd
Revises: 52731c9cf214
Create Date: 2026-06-04 06:48:14.258722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca3403245cd'
down_revision: Union[str, Sequence[str], None] = '52731c9cf214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # machineries
    op.add_column(
        'machineries',
        sa.Column(
            'operational',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    op.add_column(
        'machineries',
        sa.Column(
            'supervisor',
            sa.String(length=128),
            nullable=False,
            server_default='-'
        )
    )

    op.add_column(
        'machineries',
        sa.Column(
            'personnel',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'machineries',
        sa.Column(
            'gdzs',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    # reports
    op.add_column(
        'reports',
        sa.Column(
            'leadership',
            sa.String(length=128),
            nullable=False,
            server_default='-'
        )
    )

    # убрать server_default после заполнения существующих строк
    op.alter_column('machineries', 'operational', server_default=None)
    op.alter_column('machineries', 'supervisor', server_default=None)
    op.alter_column('machineries', 'personnel', server_default=None)
    op.alter_column('machineries', 'gdzs', server_default=None)
    op.alter_column('reports', 'leadership', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'leadership')
    op.drop_column('machineries', 'gdzs')
    op.drop_column('machineries', 'personnel')
    op.drop_column('machineries', 'supervisor')
    op.drop_column('machineries', 'operational')
    # ### end Alembic commands ###
