"""add admin in user

Revision ID: 52731c9cf214
Revises: e6ae54741e34
Create Date: 2026-04-28 12:26:17.200118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52731c9cf214'
down_revision: Union[str, Sequence[str], None] = 'e6ae54741e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку как nullable=True (временно)
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))

    # 2. Проставляем False всем существующим записям
    op.execute("UPDATE users SET admin = False")

    # 3. Устанавливаем ограничение NOT NULL после заполнения данных
    op.alter_column('users', 'admin', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
