"""add total_personnel and current_personnel

Revision ID: 6fc3fdc8c301
Revises: 2ca3403245cd
Create Date: 2026-06-04 07:08:47.133768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc3fdc8c301'
down_revision: Union[str, Sequence[str], None] = '2ca3403245cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'machineries',
        sa.Column(
            'total_personnel',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'machineries',
        sa.Column(
            'current_personnel',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.alter_column('machineries', 'total_personnel', server_default=None)
    op.alter_column('machineries', 'current_personnel', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineries', 'current_personnel')
    op.drop_column('machineries', 'total_personnel')
    # ### end Alembic commands ###
