"""update opertation and date maintenance

Revision ID: a1bc182e5344
Revises: 25625c9da1d9
Create Date: 2026-07-17 08:01:08.761828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bc182e5344'
down_revision: Union[str, Sequence[str], None] = '25625c9da1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machineries', 'operational')
    op.alter_column('maintenance', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column(
        "reports",
        sa.Column("operational_machinery", sa.Boolean(),
                  nullable=False, server_default=sa.false())
    )
    op.alter_column("reports", "operational_machinery", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'operational_machinery')
    op.alter_column('maintenance', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('machineries', sa.Column('operational', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
