"""update connection machineries and maintenance

Revision ID: e6ae54741e34
Revises: 
Create Date: 2026-04-24 14:36:43.866764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ae54741e34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_machinery_id'), table_name='maintenance')
    op.create_unique_constraint(None, 'maintenance', ['machinery_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance', type_='unique')
    op.create_index(op.f('ix_maintenance_machinery_id'), 'maintenance', ['machinery_id'], unique=False)
    # ### end Alembic commands ###
