"""add title index

Revision ID: ecdc457e8bc9
Revises: a1bc182e5344
Create Date: 2026-07-17 10:30:43.347684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdc457e8bc9'
down_revision: Union[str, Sequence[str], None] = 'a1bc182e5344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_departments_title'), 'departments', ['title'], unique=False)
    op.create_index(op.f('ix_sections_title'), 'sections', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_title'), table_name='sections')
    op.drop_index(op.f('ix_departments_title'), table_name='departments')
    # ### end Alembic commands ###
